repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pycqa/pylint
  #   rev: pylint-3.0.2
  #   hooks:
  #     - id: pylint
  #       args:
  #         - --max-line-length=80
  #         - --ignore-imports=yes
  #         - -d duplicate-code
