name: Upload Python Package

on:
  push:
    branches:
      - feature/deploy  # Change this to your branch for testing

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: publish-pip  # Specify the environment here

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: python -m twine upload --verbose dist/*
